import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Seeding database...');

  const catAlimentoSecoPerro = await prisma.category.create({
    data: { name: 'Alimentos Secos Perro', slug: 'alimentos-secos-perro', pet_type: 'dog' },
  });
  const catAlimentoSecoGato = await prisma.category.create({
    data: { name: 'Alimentos Secos Gato', slug: 'alimentos-secos-gato', pet_type: 'cat' },
  });
  const catArena = await prisma.category.create({
    data: { name: 'Arenas Sanitarias', slug: 'arenas-sanitarias', pet_type: 'cat' },
  });
  const catSnack = await prisma.category.create({
    data: { name: 'Snacks y Premios', slug: 'snacks', pet_type: 'both' },
  });
  const catAccesorio = await prisma.category.create({
    data: { name: 'Accesorios', slug: 'accesorios', pet_type: 'both' },
  });
  const catClinico = await prisma.category.create({
    data: { name: 'Prescripcion Clinica', slug: 'prescripcion-clinica', pet_type: 'dog' },
  });
  const catNutricion = await prisma.category.create({
    data: { name: 'Nutricion Natural', slug: 'nutricion-natural', pet_type: 'both' },
  });

  const products = [
    // === ALIMENTOS PERRO (4) ===
    {
      name: 'Nomade Adulto Raza Mediana y Grande',
      slug: 'nomade-adulto-raza-mediana-20kg',
      image_url: '/images/products/nomade-adulto-raza-mediana-20kg.png',
      description: 'Alimento premium con pollo fresco para perros adultos de raza mediana y grande. Sin granos, sin maiz ni soja. Rico en Omega-3 y Omega-6 para pelaje brillante.',
      category_id: catAlimentoSecoPerro.id,
      sku: 'NOM-ADU-20',
      pet_type: 'dog',
      weight_kg: 20,
      is_published: true,
      is_bestseller: true,
      badge: 'Mas vendido',
      price_one_time: 40490,
      price_autoship: 36441,
      stock_quantity: 150,
    },
    {
      name: 'Hills Science Diet Puppy Pollo',
      slug: 'hills-science-diet-puppy-pollo-1-1kg',
      image_url: '/images/products/hills-science-diet-puppy-pollo-1-1kg.png',
      description: 'Formulacion clinica para cachorros con pollo como primera proteina. DHA para desarrollo cerebral y visual. Recomendado por veterinarios.',
      category_id: catAlimentoSecoPerro.id,
      sku: 'HIL-PUP-1.1',
      pet_type: 'dog',
      weight_kg: 1.1,
      is_published: true,
      badge: 'Cachorros',
      price_one_time: 17990,
      price_autoship: 16191,
      stock_quantity: 80,
    },
    {
      name: 'Royal Canin Adult Raza Mediana',
      slug: 'royal-canin-adulto-raza-mediana-15kg',
      image_url: '/images/products/royal-canin-adulto-raza-mediana-15kg.png',
      description: 'Alimento premium para perros adultos de 1-10 anos y 11-25kg. Formula con proteina de alta digestibilidad y complejo de antioxidantes.',
      category_id: catAlimentoSecoPerro.id,
      sku: 'RC-ADU-15',
      pet_type: 'dog',
      weight_kg: 15,
      is_published: true,
      badge: null,
      price_one_time: 54990,
      price_autoship: 49491,
      stock_quantity: 90,
    },
    {
      name: 'Acana Heritage Adult Pollo y Pavo',
      slug: 'acana-heritage-adulto-pollo-pavo-11-4kg',
      image_url: '/images/products/acana-heritage-adulto-pollo-pavo-11-4kg.png',
      description: 'Alimento ultra premium con pollo y pavo fresco de granjas regionales. 50-75% ingredientes animales. Sin granos, sin gluten.',
      category_id: catAlimentoSecoPerro.id,
      sku: 'ACA-HER-11.4',
      pet_type: 'dog',
      weight_kg: 11.4,
      is_published: true,
      badge: 'Ultra Premium',
      price_one_time: 59990,
      price_autoship: 53991,
      stock_quantity: 45,
    },
    // === ALIMENTOS GATO (4) ===
    {
      name: 'N&D Prime Gato Castrado Pollo',
      slug: 'nd-prime-gato-castrado-pollo-7-5kg',
      image_url: '/images/products/nd-prime-gato-castrado-pollo-7-5kg.png',
      description: 'Alimento ultra premium para gatos castrados. Pollo monoproteina, sin granos. Formula especial para control de peso y salud urinaria.',
      category_id: catAlimentoSecoGato.id,
      sku: 'ND-CAST-7.5',
      pet_type: 'cat',
      weight_kg: 7.5,
      is_published: true,
      is_bestseller: true,
      badge: 'Premium',
      price_one_time: 62990,
      price_autoship: 56691,
      stock_quantity: 60,
    },
    {
      name: 'Nomade Gato Adulto',
      slug: 'nomade-gato-adulto-10kg',
      image_url: '/images/products/nomade-gato-adulto-10kg.png',
      description: 'Alimento premium para gatos adultos. Con pollo fresco y vegetales. Rico en taurina para salud cardiaca y visual.',
      category_id: catAlimentoSecoGato.id,
      sku: 'NOM-GAT-10',
      pet_type: 'cat',
      weight_kg: 10,
      is_published: true,
      is_bestseller: true,
      badge: 'AutoCompra',
      price_one_time: 30990,
      price_autoship: 27891,
      stock_quantity: 120,
    },
    {
      name: 'Royal Canin Gato Esterilizado',
      slug: 'royal-canin-gato-esterilizado-3-5kg',
      image_url: '/images/products/royal-canin-gato-esterilizado-3-5kg.png',
      description: 'Formula especifica para gatos esterilizados. Ayuda a mantener un peso saludable y prevenir problemas urinarios. Alta palatabilidad.',
      category_id: catAlimentoSecoGato.id,
      sku: 'RC-GAT-EST-3.5',
      pet_type: 'cat',
      weight_kg: 3.5,
      is_published: true,
      badge: 'Esterilizados',
      price_one_time: 28990,
      price_autoship: 26091,
      stock_quantity: 70,
    },
    {
      name: 'Whiskas Gato Adulto Pollo',
      slug: 'whiskas-gato-adulto-pollo-4kg',
      image_url: '/images/products/whiskas-gato-adulto-pollo-4kg.png',
      description: 'Alimento balanceado para gatos adultos con pollo. Formula con vitaminas y minerales para una vida saludable.',
      category_id: catAlimentoSecoGato.id,
      sku: 'WHI-GAT-4',
      pet_type: 'cat',
      weight_kg: 4,
      is_published: true,
      badge: 'Clasico',
      price_one_time: 15990,
      price_autoship: 14391,
      stock_quantity: 200,
    },
    // === ARENAS (3) ===
    {
      name: 'Pride Litter Natural Arena Sanitaria',
      slug: 'pride-litter-natural-arena-10kg',
      image_url: '/images/products/pride-litter-natural-arena-10kg.png',
      description: 'Arena sanitaria natural aglomerante. Biodegradable, control de olor superior. Sin polvo, segura para gatos y humanos.',
      category_id: catArena.id,
      sku: 'PRI-LIT-10',
      pet_type: 'cat',
      weight_kg: 10,
      is_published: true,
      badge: 'Eco',
      price_one_time: 12990,
      price_autoship: 11691,
      stock_quantity: 200,
    },
    {
      name: 'Sanicat Arena Aglomerante',
      slug: 'sanicat-arena-aglomerante-10kg',
      image_url: '/images/products/sanicat-arena-aglomerante-10kg.png',
      description: 'Arena aglomerante de alta calidad. Control de olores efectivo, facil de limpiar. Forma grupos compactos para una limpieza sencilla.',
      category_id: catArena.id,
      sku: 'SAN-AGR-10',
      pet_type: 'cat',
      weight_kg: 10,
      is_published: true,
      badge: 'Aglomerante',
      price_one_time: 9990,
      price_autoship: 8991,
      stock_quantity: 180,
    },
    {
      name: 'Cat\'s Best Arena Natural',
      slug: 'cats-best-arena-natural-5kg',
      image_url: '/images/products/cats-best-arena-natural-5kg.png',
      description: 'Arena natural 100% vegetal. Biodegradable, compostable. 3x mas absorbente que la arena tradicional. Ideal para hogares eco-conscientes.',
      category_id: catArena.id,
      sku: 'CAT-BEST-5',
      pet_type: 'cat',
      weight_kg: 5,
      is_published: true,
      badge: 'Eco Premium',
      price_one_time: 14990,
      price_autoship: 13491,
      stock_quantity: 100,
    },
    // === SNACKS (3) ===
    {
      name: 'Dental Stix Pack Cuidado Dental',
      slug: 'dental-stix-pack-280g',
      image_url: '/images/products/dental-stix-pack-280g.png',
      description: 'Snack dental para perros de talla mediana. Ayuda a reducir la formacion de sarro. Textura unica que limpia los dientes mientras tu perro disfruta.',
      category_id: catSnack.id,
      sku: 'DEN-STX-280',
      pet_type: 'dog',
      weight_kg: 0.28,
      is_published: true,
      badge: 'Salud Dental',
      price_one_time: 5990,
      price_autoship: 5391,
      stock_quantity: 300,
    },
    {
      name: 'Pedigree Dentastix 7 Unidades',
      slug: 'pedigree-dentastix-7-unidades',
      image_url: '/images/products/pedigree-dentastix-7-unidades.png',
      description: 'Snack dental en forma de estrella para perros. Triple accion: limpia dientes, reduce sarro y refresca el aliento.',
      category_id: catSnack.id,
      sku: 'PED-DEN-7',
      pet_type: 'dog',
      weight_kg: 0.1,
      is_published: true,
      badge: 'Dental',
      price_one_time: 4990,
      price_autoship: 4491,
      stock_quantity: 400,
    },
    {
      name: 'Greenies Snack Dental Gato',
      slug: 'greenies-snack-dental-gato-113g',
      image_url: '/images/products/greenies-snack-dental-gato-113g.png',
      description: 'Snack dental premium para gatos. Textura unica que limpia los dientes. Con clorofila natural para aliento fresco.',
      category_id: catSnack.id,
      sku: 'GRE-GAT-113',
      pet_type: 'cat',
      weight_kg: 0.113,
      is_published: true,
      badge: 'Premium',
      price_one_time: 6990,
      price_autoship: 6291,
      stock_quantity: 150,
    },
    // === ACCESORIOS (3) ===
    {
      name: 'Comedero Acero Inoxidable + Base Bambu',
      slug: 'comedero-acero-bambu-set',
      image_url: '/images/products/comedero-acero-bambu-set.png',
      description: 'Set de comedero y bebedero de acero inoxidable con base de bambu natural. Antideslizante, facil de limpiar. Diseno escandinavo minimalista.',
      category_id: catAccesorio.id,
      sku: 'ACC-COM-BAM',
      pet_type: 'both',
      weight_kg: 0.8,
      is_published: true,
      badge: 'Diseno',
      price_one_time: 18990,
      price_autoship: 17091,
      stock_quantity: 75,
    },
    {
      name: 'Cama Ortopedica Memory Foam Mediana',
      slug: 'cama-ortopedica-memory-foam-mediana',
      image_url: '/images/products/cama-ortopedica-memory-foam-mediana.png',
      description: 'Cama ortopedica con espuma viscoelastica. Alivia presion en articulaciones. Funda removible y lavable. Ideal para perros senior.',
      category_id: catAccesorio.id,
      sku: 'ACC-CAM-MEM',
      pet_type: 'dog',
      weight_kg: 3.5,
      is_published: true,
      is_bestseller: true,
      badge: 'Ortopedica',
      price_one_time: 49990,
      price_autoship: 44991,
      stock_quantity: 40,
    },
    {
      name: 'Fuente de Agua Ceramica para Gato',
      slug: 'fuente-agua-ceramica-gato',
      image_url: '/images/products/fuente-agua-ceramica-gato.png',
      description: 'Fuente de agua ceramica con filtro de carbon. 3 caudales ajustables. Promueve la hidratacion. Silenciosa y facil de limpiar.',
      category_id: catAccesorio.id,
      sku: 'ACC-FUE-CER',
      pet_type: 'cat',
      weight_kg: 1.2,
      is_published: true,
      badge: 'Hidratacion',
      price_one_time: 34990,
      price_autoship: 31491,
      stock_quantity: 55,
    },
    // === CLINICO (2) ===
    {
      name: 'Hills Prescription Diet i/d Digestive Care',
      slug: 'hills-prescription-diet-id-digestive-1-5kg',
      image_url: '/images/products/hills-prescription-diet-id-digestive-1-5kg.png',
      description: 'Alimento clinico para perros con problemas digestivos. Formula de facil digestion con prebioticos y electrolitos. Solo bajo recomendacion veterinaria.',
      category_id: catClinico.id,
      sku: 'HIL-ID-1.5',
      pet_type: 'dog',
      weight_kg: 1.5,
      is_published: true,
      badge: 'Clinico',
      price_one_time: 22990,
      price_autoship: 20691,
      stock_quantity: 30,
    },
    {
      name: 'Royal Canin Gastro Intestinal',
      slug: 'royal-canin-gastro-intestinal-2kg',
      image_url: '/images/products/royal-canin-gastro-intestinal-2kg.png',
      description: 'Formula clinica para trastornos gastrointestinales. Alta digestibilidad y contenido equilibrado de fibras. Exclusivo bajo recomendacion vet.',
      category_id: catClinico.id,
      sku: 'RC-GAS-2',
      pet_type: 'dog',
      weight_kg: 2,
      is_published: true,
      badge: 'Veterinario',
      price_one_time: 25990,
      price_autoship: 23391,
      stock_quantity: 35,
    },
    // === NUTRICION NATURAL (3) ===
    {
      name: 'Caldo de Colageno Natural para Perros',
      slug: 'caldo-colageno-natural-perros-1l',
      image_url: '/images/products/caldo-colageno-natural-perros-1l.png',
      description: 'Caldo de huesos 100% natural. Rico en colageno, glucosamina y condroitina. Beneficioso para articulaciones, piel y digestion. Sin conservantes.',
      category_id: catNutricion.id,
      sku: 'NUT-CAL-1L',
      pet_type: 'dog',
      weight_kg: 1,
      is_published: true,
      badge: 'Superfood',
      price_one_time: 12990,
      price_autoship: 11691,
      stock_quantity: 80,
    },
    {
      name: 'Snacks Liofilizados Salmon 100% Natural',
      slug: 'snacks-liofilizados-salmon-100g',
      image_url: '/images/products/snacks-liofilizados-salmon-100g.png',
      description: 'Snacks de salmon liofilizado. Unico ingrediente: salmon salvaje. Alto en Omega-3, sin conservantes ni aditivos. Entrenamiento y premiun.',
      category_id: catNutricion.id,
      sku: 'NUT-LIO-SAL',
      pet_type: 'both',
      weight_kg: 0.1,
      is_published: true,
      is_bestseller: true,
      badge: 'Natural',
      price_one_time: 9990,
      price_autoship: 8991,
      stock_quantity: 120,
    },
    {
      name: 'Aceite de Salmon Omega-3 para Mascotas',
      slug: 'aceite-salmon-omega3-mascotas-500ml',
      image_url: '/images/products/aceite-salmon-omega3-mascotas-500ml.png',
      description: 'Aceite puro de salmon chileno. Rico en Omega-3, EPA y DHA. Mejora pelaje, piel y salud articular. Sin colorantes ni saborizantes.',
      category_id: catNutricion.id,
      sku: 'NUT-ACE-500',
      pet_type: 'both',
      weight_kg: 0.5,
      is_published: true,
      badge: 'Suplemento',
      price_one_time: 15990,
      price_autoship: 14391,
      stock_quantity: 90,
    },
  ];

  for (const product of products) {
    await prisma.product.create({ data: product });
    console.log(`  ✅ ${product.name}`);
  }

  const allProducts = await prisma.product.findMany();

  const reviews = [
    {
      product_id: allProducts[0].id,
      rating: 5,
      title: 'Mi perro lo ama',
      content: 'Mi Golden Retriever paso de tener piel seca a un pelaje brillante en 3 semanas. La calidad del alimento se nota. Recomendado 100%.',
      pet_name: 'Max',
      pet_breed: 'Golden Retriever',
      is_verified: true,
      is_published: true,
    },
    {
      product_id: allProducts[0].id,
      rating: 5,
      title: 'Excelente relacion calidad-precio',
      content: 'Llevo 6 meses con AutoCompra y nunca me he quedado sin alimento. El descuento del 10% se nota en el bolsillo.',
      pet_name: 'Luna',
      pet_breed: 'Labrador',
      is_verified: true,
      is_published: true,
    },
    {
      product_id: allProducts[4].id,
      rating: 5,
      title: 'Mi gato castrado por fin come bien',
      content: 'Desde que cambie a N&D Prime mi gato no ha tenido problemas urinarios. El veterinario quedo impresionado con sus examenes.',
      pet_name: 'Michi',
      pet_breed: 'Europeo Comun',
      is_verified: true,
      is_published: true,
    },
    {
      product_id: allProducts[5].id,
      rating: 4,
      title: 'Buen alimento, precio justo',
      content: 'Mis dos gatos comen Nomade hace un ano. Buen pelo, buena energia. Lo unico que mejoraria es el packaging.',
      pet_name: 'Simba y Nala',
      pet_breed: 'Siames',
      is_verified: true,
      is_published: true,
    },
    {
      product_id: allProducts[14].id,
      rating: 5,
      title: 'Mi perro senior duerme como un angel',
      content: 'Compre esta cama para mi pastor aleman de 11 anos. Desde que la tiene, duerme toda la noche sin quejarse. La espuma viscoelastica es increible.',
      pet_name: 'Toby',
      pet_breed: 'Pastor Aleman',
      is_verified: true,
      is_published: true,
    },
    {
      product_id: allProducts[19].id,
      rating: 5,
      title: 'Los snacks mas naturales que he visto',
      content: 'Un solo ingrediente: salmon. Mis gatos vuelven locos por estos snacks. Perfectos para entrenamiento.',
      pet_name: 'Milo y Lola',
      pet_breed: 'Maine Coon',
      is_verified: true,
      is_published: true,
    },
    {
      product_id: allProducts[12].id,
      rating: 4,
      title: 'Mi gato lo acepto bien',
      content: 'No es facil encontrar snacks dentales que los gatos acepten. Estos Greenies si les gustaron. Se nota el aliento mas fresco.',
      pet_name: 'Pelusa',
      pet_breed: 'Persa',
      is_verified: true,
      is_published: true,
    },
  ];

  for (const review of reviews) {
    await prisma.review.create({ data: review });
    console.log(`  ✅ Review: ${review.title}`);
  }

  console.log(`🎉 Database seeded! ${products.length} productos, ${reviews.length} reviews`);
}

main()
  .catch((e) => {
    console.error('❌ Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
